#ifndef HAND_PARAMETERS_H
#define HAND_PARAMETERS_H

enum
{
    ASTRA_PARAMETER_DEBUG_HAND_VIEW_TYPE = 0,
    ASTRA_PARAMETER_DEBUG_HAND_USE_MOUSE_PROBE = 1,
    ASTRA_PARAMETER_DEBUG_HAND_MOUSE_NORM_POSITION = 2,
    ASTRA_PARAMETER_HAND_INCLUDE_CANDIDATE_POINTS = 3,
    ASTRA_PARAMETER_DEBUG_HAND_PAUSE_INPUT = 4,
    ASTRA_PARAMETER_DEBUG_HAND_LOCK_SPAWN_POINT = 5,
};

#endif /* HAND_PARAMETERS_H */
