#ifndef IMAGE_PARAMETERS_H
#define IMAGE_PARAMETERS_H

enum {
    ASTRA_PARAMETER_IMAGE_HFOV = 0,
    ASTRA_PARAMETER_IMAGE_VFOV = 1,
    ASTRA_PARAMETER_IMAGE_MIRRORING = 2,
    ASTRA_PARAMETER_IMAGE_MODES = 3,
    ASTRA_PARAMETER_IMAGE_MODE = 4
};

#endif /* IMAGE_PARAMETERS_H */
